"""Initial database schema

Revision ID: 57ea1b4229e8
Revises: 
Create Date: 2025-09-02 17:26:27.154427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ea1b4229e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_authorinfo',
    sa.Column('author_code', sa.String(length=30), nullable=False, comment='권한코드'),
    sa.Column('author_nm', sa.String(length=60), nullable=False, comment='권한명'),
    sa.Column('author_dc', sa.String(length=200), nullable=True, comment='권한설명'),
    sa.Column('author_creat_de', sa.DateTime(), nullable=False, comment='권한생성일'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=False, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.PrimaryKeyConstraint('author_code'),
    schema='skybootcore',
    comment='권한정보'
    )
    op.create_table('tb_bbsmaster',
    sa.Column('bbs_id', sa.String(length=30), nullable=False, comment='게시판ID'),
    sa.Column('bbs_nm', sa.String(length=255), nullable=False, comment='게시판명'),
    sa.Column('bbs_intrcn', sa.String(length=2400), nullable=True, comment='게시판소개'),
    sa.Column('bbs_ty_code', sa.String(length=6), nullable=False, comment='게시판유형코드'),
    sa.Column('reply_posbl_at', sa.String(length=1), nullable=False, comment='답장가능여부'),
    sa.Column('file_atch_posbl_at', sa.String(length=1), nullable=False, comment='파일첨부가능여부'),
    sa.Column('atch_posbl_file_size', sa.Numeric(precision=8), nullable=True, comment='첨부가능파일사이즈'),
    sa.Column('use_at', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('delete_at', sa.String(length=1), nullable=False, comment='삭제여부'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=False, comment='최초등록자ID'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.PrimaryKeyConstraint('bbs_id'),
    schema='skybootcore',
    comment='게시판마스터'
    )
    op.create_table('tb_cmmn_grp_code',
    sa.Column('code_id', sa.String(length=6), nullable=False, comment='코드ID'),
    sa.Column('code_id_nm', sa.String(length=60), nullable=True, comment='코드ID명'),
    sa.Column('code_id_dc', sa.String(length=200), nullable=True, comment='코드ID설명'),
    sa.Column('use_yn', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('cl_code', sa.String(length=10), nullable=True, comment='분류코드'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=True, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.PrimaryKeyConstraint('code_id'),
    schema='skybootcore',
    comment='공통코드'
    )
    op.create_index('ix_cmmn_grp_code_01', 'tb_cmmn_grp_code', ['cl_code'], unique=False, schema='skybootcore')
    op.create_table('tb_file',
    sa.Column('atch_file_id', sa.String(length=20), nullable=False, comment='첨부파일ID'),
    sa.Column('creat_dt', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('use', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=False, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.PrimaryKeyConstraint('atch_file_id'),
    schema='skybootcore',
    comment='파일속성'
    )
    op.create_table('tb_loginlog',
    sa.Column('log_id', sa.String(length=20), nullable=False, comment='로그ID'),
    sa.Column('conect_id', sa.String(length=20), nullable=True, comment='접속ID'),
    sa.Column('conect_ip', sa.String(length=23), nullable=True, comment='접속IP'),
    sa.Column('conect_mthd', sa.String(length=4), nullable=True, comment='접속방식'),
    sa.Column('error_occrrnc_at', sa.String(length=1), nullable=True, comment='오류발생여부'),
    sa.Column('error_code', sa.String(length=3), nullable=True, comment='오류코드'),
    sa.Column('creat_dt', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=True, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='skybootcore',
    comment='접속로그'
    )
    op.create_table('tb_menuinfo',
    sa.Column('menu_no', sa.String(), nullable=False, comment='메뉴번호'),
    sa.Column('menu_nm', sa.String(length=60), nullable=False, comment='메뉴명'),
    sa.Column('progrm_file_nm', sa.String(length=60), nullable=False, comment='프로그램파일명'),
    sa.Column('upper_menu_no', sa.String(), nullable=True, comment='상위메뉴번호'),
    sa.Column('menu_ordr', sa.Numeric(precision=5), nullable=False, comment='메뉴순서'),
    sa.Column('menu_dc', sa.String(length=250), nullable=True, comment='메뉴설명'),
    sa.Column('relate_image_path', sa.String(length=100), nullable=True, comment='관계이미지경로'),
    sa.Column('relate_image_nm', sa.String(length=60), nullable=True, comment='관계이미지명'),
    sa.Column('display_yn', sa.String(length=1), nullable=False, comment='메뉴표시여부'),
    sa.Column('use_tag_yn', sa.String(length=1), nullable=False, comment='메뉴 표시할때 이미지 URL 대신 태그내용를 사용하는지 여부표시'),
    sa.Column('menu_tag', sa.String(), nullable=True, comment='메뉴 표시 태그 use_tag_yn 이 Y 일때 사용'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.ForeignKeyConstraint(['upper_menu_no'], ['skybootcore.tb_menuinfo.menu_no'], ),
    sa.PrimaryKeyConstraint('menu_no'),
    schema='skybootcore',
    comment='메뉴정보'
    )
    op.create_index('ix_menuinfo_01', 'tb_menuinfo', ['upper_menu_no'], unique=False, schema='skybootcore')
    op.create_table('tb_authormenu',
    sa.Column('author_code', sa.String(length=30), nullable=False, comment='권한코드'),
    sa.Column('menu_no', sa.String(length=7), nullable=False, comment='메뉴번호'),
    sa.Column('work_auth_code', sa.String(length=15), nullable=False, comment='작업권한'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.ForeignKeyConstraint(['author_code'], ['skybootcore.tb_authorinfo.author_code'], ),
    sa.ForeignKeyConstraint(['menu_no'], ['skybootcore.tb_menuinfo.menu_no'], ),
    sa.PrimaryKeyConstraint('author_code', 'menu_no'),
    schema='skybootcore',
    comment='권한메뉴'
    )
    op.create_index('ix_authormenu_01', 'tb_authormenu', ['menu_no'], unique=False, schema='skybootcore')
    op.create_index('ix_authormenu_02', 'tb_authormenu', ['author_code'], unique=False, schema='skybootcore')
    op.create_table('tb_bbs',
    sa.Column('ntt_id', sa.Numeric(precision=20), nullable=False, comment='게시물ID'),
    sa.Column('bbs_id', sa.String(length=30), nullable=False, comment='게시판ID'),
    sa.Column('ntt_no', sa.Numeric(precision=20), nullable=True, comment='게시물번호'),
    sa.Column('ntt_sj', sa.String(length=2000), nullable=True, comment='게시물제목'),
    sa.Column('ntt_cn', sa.Text(), nullable=True, comment='게시물내용'),
    sa.Column('answer_at', sa.String(length=1), nullable=True, comment='댓글여부'),
    sa.Column('parntsctt_no', sa.Numeric(precision=10), nullable=True, comment='부모글번호'),
    sa.Column('answer_lc', sa.Numeric(precision=8), nullable=True, comment='댓글위치'),
    sa.Column('sort_ordr', sa.Numeric(precision=8), nullable=True, comment='정렬순서'),
    sa.Column('rdcnt', sa.Numeric(precision=10), nullable=True, comment='조회수'),
    sa.Column('use_at', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('ntce_bgnde', sa.String(length=20), nullable=True, comment='게시시작일'),
    sa.Column('ntce_endde', sa.String(length=20), nullable=True, comment='게시종료일'),
    sa.Column('ntcr_id', sa.String(length=20), nullable=True, comment='게시자ID'),
    sa.Column('ntcr_nm', sa.String(length=20), nullable=True, comment='게시자명'),
    sa.Column('password', sa.String(length=200), nullable=True, comment='비밀번호'),
    sa.Column('atch_file_id', sa.String(length=20), nullable=True, comment='첨부파일ID'),
    sa.Column('notice_at', sa.String(length=1), nullable=True, comment='공지사항여부'),
    sa.Column('sj_bold_at', sa.String(length=1), nullable=True, comment='제목볼드여부'),
    sa.Column('secret_at', sa.String(length=1), nullable=True, comment='비밀글여부'),
    sa.Column('blog_id', sa.String(length=20), nullable=True, comment='블로그 ID'),
    sa.Column('delete_at', sa.String(length=1), nullable=True, comment='삭제여부'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=False, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.ForeignKeyConstraint(['bbs_id'], ['skybootcore.tb_bbsmaster.bbs_id'], ),
    sa.PrimaryKeyConstraint('ntt_id', 'bbs_id'),
    schema='skybootcore',
    comment='게시판'
    )
    op.create_index('ix_bbs_01', 'tb_bbs', ['bbs_id'], unique=False, schema='skybootcore')
    op.create_table('tb_cmmn_code',
    sa.Column('code_id', sa.String(length=6), nullable=False, comment='코드ID'),
    sa.Column('code', sa.String(length=15), nullable=False, comment='코드'),
    sa.Column('code_nm', sa.String(length=60), nullable=True, comment='코드명'),
    sa.Column('code_dc', sa.String(length=200), nullable=True, comment='코드설명'),
    sa.Column('attr1', sa.String(length=20), nullable=True, comment='속성1'),
    sa.Column('attr2', sa.String(length=20), nullable=True, comment='속성2'),
    sa.Column('attr3', sa.String(length=20), nullable=True, comment='속성3'),
    sa.Column('attr4', sa.String(length=20), nullable=True, comment='속성4'),
    sa.Column('use_yn', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('code_ordr', sa.Integer(), nullable=True, comment='코드순서'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=True, comment='최초등록시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.ForeignKeyConstraint(['code_id'], ['skybootcore.tb_cmmn_grp_code.code_id'], ),
    sa.PrimaryKeyConstraint('code_id', 'code'),
    schema='skybootcore',
    comment='공통상세코드'
    )
    op.create_index('ix_cmmn_code_01', 'tb_cmmn_code', ['code_id'], unique=False, schema='skybootcore')
    op.create_table('tb_filedetail',
    sa.Column('atch_file_id', sa.String(length=20), nullable=False, comment='첨부파일ID'),
    sa.Column('file_sn', sa.Numeric(precision=10), nullable=False, comment='파일순번'),
    sa.Column('file_stre_cours', sa.String(length=2000), nullable=False, comment='파일저장경로'),
    sa.Column('stre_file_nm', sa.String(length=255), nullable=False, comment='저장파일명'),
    sa.Column('orignl_file_nm', sa.String(length=255), nullable=True, comment='원파일명'),
    sa.Column('file_extsn', sa.String(length=20), nullable=False, comment='파일확장자'),
    sa.Column('file_cn', sa.Text(), nullable=True, comment='파일내용'),
    sa.Column('file_size', sa.Numeric(precision=8), nullable=True, comment='파일크기'),
    sa.Column('file_delete_yn', sa.String(length=1), nullable=False, comment='파일삭제삭제여부'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.ForeignKeyConstraint(['atch_file_id'], ['skybootcore.tb_file.atch_file_id'], ),
    sa.PrimaryKeyConstraint('atch_file_id', 'file_sn'),
    schema='skybootcore',
    comment='파일상세정보'
    )
    op.create_index('ix_filedetail_01', 'tb_filedetail', ['atch_file_id'], unique=False, schema='skybootcore')
    op.create_table('tb_comment',
    sa.Column('ntt_id', sa.Numeric(precision=20), nullable=False, comment='게시물ID'),
    sa.Column('bbs_id', sa.String(length=30), nullable=False, comment='게시판ID'),
    sa.Column('answer_no', sa.Numeric(precision=20), nullable=False, comment='댓글번호'),
    sa.Column('wrter_id', sa.String(length=20), nullable=True, comment='작성자ID'),
    sa.Column('wrter_nm', sa.String(length=20), nullable=True, comment='작성자명'),
    sa.Column('answer', sa.String(length=2000), nullable=True, comment='댓글'),
    sa.Column('use_at', sa.String(length=1), nullable=False, comment='사용여부'),
    sa.Column('password', sa.String(length=200), nullable=True, comment='비밀번호'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=False, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.ForeignKeyConstraint(['ntt_id', 'bbs_id'], ['skybootcore.tb_bbs.ntt_id', 'skybootcore.tb_bbs.bbs_id'], ),
    sa.PrimaryKeyConstraint('ntt_id', 'bbs_id', 'answer_no'),
    schema='skybootcore',
    comment='댓글'
    )
    op.create_index('ix_comment_01', 'tb_comment', ['ntt_id', 'bbs_id'], unique=False, schema='skybootcore')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_01', table_name='tb_comment', schema='skybootcore')
    op.drop_table('tb_comment', schema='skybootcore')
    op.drop_index('ix_filedetail_01', table_name='tb_filedetail', schema='skybootcore')
    op.drop_table('tb_filedetail', schema='skybootcore')
    op.drop_index('ix_cmmn_code_01', table_name='tb_cmmn_code', schema='skybootcore')
    op.drop_table('tb_cmmn_code', schema='skybootcore')
    op.drop_index('ix_bbs_01', table_name='tb_bbs', schema='skybootcore')
    op.drop_table('tb_bbs', schema='skybootcore')
    op.drop_index('ix_authormenu_02', table_name='tb_authormenu', schema='skybootcore')
    op.drop_index('ix_authormenu_01', table_name='tb_authormenu', schema='skybootcore')
    op.drop_table('tb_authormenu', schema='skybootcore')
    op.drop_index('ix_menuinfo_01', table_name='tb_menuinfo', schema='skybootcore')
    op.drop_table('tb_menuinfo', schema='skybootcore')
    op.drop_table('tb_loginlog', schema='skybootcore')
    op.drop_table('tb_file', schema='skybootcore')
    op.drop_index('ix_cmmn_grp_code_01', table_name='tb_cmmn_grp_code', schema='skybootcore')
    op.drop_table('tb_cmmn_grp_code', schema='skybootcore')
    op.drop_table('tb_bbsmaster', schema='skybootcore')
    op.drop_table('tb_authorinfo', schema='skybootcore')
    # ### end Alembic commands ###
