"""Add API usage log table

Revision ID: 5b47b309eaff
Revises: 65b35bbc3b10
Create Date: 2025-09-05 09:09:33.544940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b47b309eaff'
down_revision: Union[str, None] = '65b35bbc3b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_api_usage_log',
    sa.Column('log_id', sa.String(length=20), nullable=False, comment='로그ID'),
    sa.Column('user_id', sa.String(length=20), nullable=True, comment='사용자ID'),
    sa.Column('endpoint', sa.String(length=200), nullable=False, comment='API 엔드포인트'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 메서드'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='클라이언트 IP 주소'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='사용자 에이전트'),
    sa.Column('request_body', sa.Text(), nullable=True, comment='요청 본문'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='응답 상태 코드'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='응답 시간(밀리초)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('frst_regist_pnttm', sa.DateTime(), nullable=True, comment='최초등록시점'),
    sa.Column('frst_register_id', sa.String(length=20), nullable=True, comment='최초등록자ID'),
    sa.Column('last_updt_pnttm', sa.DateTime(), nullable=True, comment='최종수정시점'),
    sa.Column('last_updusr_id', sa.String(length=20), nullable=True, comment='최종수정자ID'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='skybootcore',
    comment='API 사용 로그'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_api_usage_log', schema='skybootcore')
    # ### end Alembic commands ###
