"""Create tables from models

Revision ID: 65b35bbc3b10
Revises: 57ea1b4229e8
Create Date: 2025-09-02 17:35:57.478229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b35bbc3b10'
down_revision: Union[str, None] = '57ea1b4229e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 테이블들은 이미 57ea1b4229e8 마이그레이션에서 생성되었으므로 중복 생성 제거
    # 이 마이그레이션은 실제로는 아무것도 하지 않음 (빈 마이그레이션)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 이 마이그레이션은 실제로는 아무것도 하지 않았으므로 downgrade도 아무것도 하지 않음
    pass
    # ### end Alembic commands ###
